包括内容：numpy包，pandas包，数据储存类型【list, array, DataFrame】，子方程

Python的厉害之处在于可以引用各种各样的包，每个包中有各种各样的方程。学过R的BA的同学对这一点比较熟悉，和R特别像。

这一个note主要讲一下 numpy，pandas这两个最为基础的包。

讲这两个包的同时还需要讲一下另一个编程里面非常重要的概念，叫做数据类型。这我也感打包票BA的同学就算学过R也不太清楚的概念。不同的数据会用不同的格式存储在电脑里，所以调用的方式，计算的方法都不太一样。这一点是python好也是python不好的地方。C语言麻烦的地方在于任何一个赋值都要首先定义数据类型，而python不需要。缺点就是，C语言你一眼就知道自己数据类型用对了没有，而python不行。

numpy是一个数学包，除了一堆数学操作以外，还引入了一个数据类型叫做array。pandas是数据包，主要是针对数据操作的方程，引入了一个数据类型叫做dataframe。

In [1]:
import numpy as np
import pandas as pd

list，array，dataframe是三个目前为止学到的最基本储存数据的格式。三个数据结构都具有无限扩展的能力。下面来看看三个结构有什么区别。

In [3]:
a=[0,1,2,3,4,5]
b=np.array([0,1,2,3,4,5])
c=pd.DataFrame([0,1,2,3,4,5])
print(type(a))
print(type(b))
print(type(c))

<class 'list'>
<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>


list是最简单的数据储存类型，python自带，无须开包。优点就是简单。由于估计没有什么人学过数据结构，具体的一些细节我就不陈述，只讲一些基本的。

list介绍https://docs.python.org/2/tutorial/datastructures.html

list一般常用方程：

In [40]:
lista=[]              #新建list
lista = lista + ['a'] #增加一个值
print(lista)

['a']


In [41]:
lista.insert(1,'b')   #增加一个值
print(lista)

['a', 'b']


In [42]:
lista.append('c')     #增加一个值
print(lista)

['a', 'b', 'c']


In [43]:
lista.extend('d')     #增加一个值
print(lista)

['a', 'b', 'c', 'd']


四个方程，区别是什么。

先来说append, append()方程是在list末尾加一个东西。注意，是加一个东西，不管你输入什么，都是加入一个东西。如何看每个单位？看逗号。逗号之间的都是一个单位。没有逗号？恭喜你，你插入了一整个东西。

In [44]:
lista.append([1,2,3,4,5,6])
print(lista)
#可以看到，[1,2,3,4,5,6]是作为一整个整体加入到list末尾

['a', 'b', 'c', 'd', [1, 2, 3, 4, 5, 6]]


+操作和extend的本质是一样的，原则上就是把两个list拼接在一起。不同的是，extend可以识别单个元素，而+后面的东西必须是list格式。另一个要注意的是，+操作需要有等号。

In [46]:
lista+[1,2,3,4,5]
print(lista)      #没有加=等于在做无用功
lista=lista+[1,2,3,4,5]
print(lista)

['a', 'b', 'c', 'd', [1, 2, 3, 4, 5, 6]]
['a', 'b', 'c', 'd', [1, 2, 3, 4, 5, 6], 1, 2, 3, 4, 5]


In [47]:
lista+'a'

TypeError: can only concatenate list (not "str") to list

In [64]:
lista.extend('a') #extend可以识别单个元素
print(lista)

['a', 'b', 'c', 'd', [1, 2, 3, 4, 5, 6], 1, 2, 3, 4, 5, 'a']


In [65]:
lista.extend('b','c')

TypeError: extend() takes exactly one argument (2 given)

In [66]:
lista.extend(['b','c']) #需要插入两个元素，需要以list的形式输入
print(lista)

['a', 'b', 'c', 'd', [1, 2, 3, 4, 5, 6], 1, 2, 3, 4, 5, 'a', 'b', 'c']


不同于append，extend，insert可以在任意位置插入一个新的元素。格式为insert(制定index，值），同样，insert也是插入一个整体，而不是一段list

In [72]:
lista.insert(0,[1,2,3,4,5])
print(lista)

[[1, 2, 3, 4, 5], 'a', 'b', 'c', 'd', [1, 2, 3, 4, 5, 6], 1, 2, 3, 4, 5, 'a', 'b', 'c']


删除元素。三个方法，del， .remove(), .pop()

del 是对内存进行操作，可以直接制定删除的元素所在位置。

.remove, list结构下的方程，删除第一个要求删除的元素，用于出现重复元素的情况下。

.pop, list结构下的方程，删除最后一个元素。

注意，list下的方程要用“.”来调用，python自带方程不用。

In [74]:
del lista[5] #删除index为5，也就是第六个元素
print(lista)

[[1, 2, 3, 4, 5], 'a', 'b', 'c', 'd', 1, 2, 3, 4, 5, 'a', 'b', 'c']


In [77]:
lista.remove('a') #删除第一个'a'
print(lista)

[[1, 2, 3, 4, 5], 'b', 'c', 'd', 1, 2, 3, 4, 5, 'a', 'b', 'c']


In [78]:
lista.pop() #删除最后一个元素
print(lista)

[[1, 2, 3, 4, 5], 'b', 'c', 'd', 1, 2, 3, 4, 5, 'a', 'b']


In [80]:
lista.remove([1,2,3,4,5]) #制定删除元素可以是很复杂的元素
print(lista)

['b', 'c', 'd', 1, 2, 3, 4, 5, 'a', 'b']


In [81]:
lista.remove("e") #remove不存在的元素会产生error

ValueError: list.remove(x): x not in list

这里我把list比较难懂的几个方程列一下并解释清楚。其实学习方程最好的办法就是试错。其他的方程很简单，大家自己看着上面post的网页，自己试错就可以了。编程一点都不难学，不但试错，试多了就知道为什么了。

第二个结构是numpy，其实运算的方程特别好讲，而且没有具体的例子，干说很无聊，所以这里还是关注在数据结构上面。numpy引入的数据结构叫做array.

array方程介绍https://docs.python.org/2/library/array.html

In [86]:
listb=[[1,2],[3,4],[5,6]]
arrayb=np.array([[1,2],[3,4],[5,6]])
print(type(listb))
print(listb)
print(type(arrayb))
print(arrayb)

<class 'list'>
[[1, 2], [3, 4], [5, 6]]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]


In [91]:
print(listb[1])
print(arrayb[1])

[3, 4]
[3 4]


In [94]:
print(listb[1][1])
print(arrayb[1][1])

4
4


In [98]:
arrayc=np.array([[1,2],[1,2,3]])
print(arrayc)

[[1, 2] [1, 2, 3]]


在构建上，array和list一样自由。在引用数据上，基本没差，只有一个小差别是，list要把行列两个index单独写：

In [103]:
listb[1,1]

TypeError: list indices must be integers or slices, not tuple

In [104]:
arrayb[1,1]

4

array牛逼的地方在于，当矩阵的大小比较规则，也就是每一行一样大，每一列一样大的时候，array就转换成了矩阵，可以进行矩阵运算。矩阵运算会在之后提到，这里不提。而list，就算符合上面的条件，还是list，不能进行矩阵操作。

In [105]:
listb @ listb     #@是矩阵乘法操作，list无法进行

TypeError: unsupported operand type(s) for @: 'list' and 'list'

In [108]:
arrayb.T @ arrayb #不用管结果是什么，反正在合适的情况下能跑矩阵操作

array([[35, 44],
       [44, 56]])

In [111]:
arrayb[0] #引用行

array([1, 2])

In [114]:
arrayb[:,0] #引用列

array([1, 3, 5])

注意在任何情况下，list，array，dataframe都一样，index输入的顺序都是行在前，列在后。所以要引用列，要先用":"把行全引用，然后用","区别行index和列index，最后输入需要引用的列。

In [121]:
arrayc=np.array([['a','b'],['c','d']])
print(arrayc)
print(type(arrayc))

[['a' 'b']
 ['c' 'd']]
<class 'numpy.ndarray'>


因为 + 也是矩阵操作，所以list和矩阵型的array 在对于 + 是不一样的。

In [123]:
print(listb+listb)

[[1, 2], [3, 4], [5, 6], [1, 2], [3, 4], [5, 6]]


In [124]:
print(arrayb+arrayb)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [125]:
print(arrayc+arrayb) #非矩阵型array不存在基础运算。

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

除了运算，另一个表现就在于array有shape，list只有长度。array不仅有shape，还能改变shape.

In [127]:
arrayb.shape

(3, 2)

In [128]:
arrayb.shape=(2,3)
arrayb

array([[1, 2, 3],
       [4, 5, 6]])

关于shape，注意看Note1中关于shape的陈述。注意，这里的(2,3)实际上是表示大小的自变量，并不是一个list或者array，所以用小括号，而不是中括号。同样的东西还出现在.ones()和.zeros()里面

In [134]:
one4_3=np.ones((4,3))
one4_3

SyntaxError: can't assign to operator (<ipython-input-134-fde94f7b57c2>, line 1)

In [136]:
zero1_6=np.zeros(6) #这两个方程都可以自动识别单行或单列array，不需要输入()，只需要输入长度。
zero1_6

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [137]:
print(zero1_6.shape)
print(zero1_6.T.shape) #.T代表把行矩阵变成列矩阵，可见这里shape并没有改变，所以在python里面，单列矩阵和单行矩阵是同一个东西。

(6,)
(6,)


最后一个数据类型是dataframe。dataframe就是在array的基础上增加行和列的index名字

In [139]:
dfc=pd.DataFrame([[1,2],[3,4],[5,6]],index=['a','b','c'],columns=['A','B'])
dfc

A  B
a  1  2
b  3  4
c  5  6

加了index就是totally两个数据类型。先来说第一点：引用。从前在array上非常方便的引用方式再也不适用了。

In [140]:
dfc[1][1] 

KeyError: 1

In [141]:
dfc[1,1]

KeyError: (1, 1)

In [142]:
dfc[1]

KeyError: 1

但是，list，array，dataframe都可以连续引用。注意连续引用是左闭右开区间。

In [145]:
print(listb[0:2])
print(arrayb[0:2])
print(dfc[0:2])

[[1, 2], [3, 4]]
[[1 2 3]
 [4 5 6]]
   A  B
a  1  2
b  3  4


但是在DataFrame，因为index的存在，单列的引用就很简单了。

In [147]:
dfc['A']

a    1
b    3
c    5
Name: A, dtype: int64

In [151]:
dfc.A

a    1
b    3
c    5
Name: A, dtype: int64

In [161]:
dfc[['B','A']] #还可以跨列引用，顺便调换列的位置。

B  A
a  2  1
b  4  3
c  6  5

那么对于单个数据呢？两个方法loc,和iloc。iloc全程就是integer loc,也就是用数字定位。

In [165]:
print(dfc.loc['a','A'])
print(dfc.iloc[0,0])
print(dfc.iloc[[0,2],[1,0]]) #同样可以跨行跨列引用

1
1
   B  A
a  2  1
c  6  5


对于单独的引用的一行或者一列，有一个新的数据类型叫做series。series不同于list的地方在于，series是有index。series同时支持index数字引用和index名字引用

In [186]:
listd=[1,3,5]
print('list:')
print(listd)
seriesd=dfc.B
print('series')
print(seriesd)

list:
[1, 3, 5]
series
a    2
b    4
c    6
Name: B, dtype: int64


In [189]:
print(seriesd[1])
print(seriesd['b'])

4
4


DataFrame还有一个更简单的操作，就是直接添加列

In [184]:
print(dfc)
dfc['C']=[3,4,5]
print(dfc)

   A  B
a  1  2
b  3  4
c  5  6
   A  B  C
a  1  2  3
b  3  4  4
c  5  6  5


这一篇只讲数据结构，之后再讲DataFrame的具体细节。